# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    cmds:
      - go build serve.go

  serve:
    cmds:
      - ./serve{{ .EXTENSION }}
    vars:
      EXTENSION: '{{ if eq OS "windows" }}.exe{{ end }}'
